### ISSUE TITLE
Image Import via HTTP improved

### ISSUE THREAD

**Issue by avstudnitz** [avstudnitz/AvS_FastSimpleImport#108]
I have refactored the image import functionality for two purposes:
- Autofill the fields `_media_attribute_id`, `_media_is_disabled`, `_media_position` and `_media_lable` with default values (fc8c052)
- You can now define the target filename of downloaded images, they can differ from the source url. Example:

```
        '_media_image' => 'http://upload.wikimedia.org/wikipedia/meta/6/6d/Wikipedia_wordmark_1x.png',
        '_media_target_filename' => 'wikipedia.jpg',
        'image' => 'wikipedia.jpg',
        'small_image' => 'wikipedia.jpg',
        'thumbnail' => 'wikipedia.jpg',
```

(958f61b)

Any comments? Tests? Improvements? Branch "develop".

**Comment by maddyBoy** [comment]
how can i use dropbox image link to to use in product csv  import magento 1.9

**Comment by maddyBoy** [comment]
( [Category does not exists] => Array ( [0] => 1 [1] => 2 [2] => 3 [3] => 4 [4] => 5 [5] => 6 [6] => 7 [7] => 8 [8] => 9 [9] => 10 ) )  when i run test.php
