### ISSUE TITLE
Image import does not appear to work in Magento 1.9 / 1.14

### ISSUE THREAD

**Issue by jonathanvaughn** [avstudnitz/AvS_FastSimpleImport#120]
Code that worked fine in 1.8/1.13 appears to not be working on the new versions - images are not imported. Everything\* else appears to be. (\* at least, products are created and appear as they should in the catalog, I haven't verified all attributes are set correctly)

Diffing the app/code/core/Mage/ImportExport between the versions doesn't appear to have any changes, and nothing is logged to PHP error log or Magento error logs. I'm not sure where the issue is.

Example of a single product with single image being imported (same thing happens for multiple and multiple)

``` php
array (
  0 =>
  array (
    'sku' => 'testSKU',
    '_type' => 'simple',
    '_attribute_set' => 'Default',
    '_product_websites' =>
    array (
      0 => 'base',
    ),
    'name' => '{{randtext}}',
    'price' => 0,
    'description' => '{{randtext}}',
    'short_description' => '{{randtext}}',
    'weight' => 0,
    'status' => 1,
    'visibility' => 4,
    'tax_class_id' => '2',
    'is_in_stock' => 1,
    'qty' => 42,
    '_category' =>
    array (
      0 => 'Women',
... (all the categories in the 1.9 sample data)
      26 => 'Men/Blazers',
    ),
    '_media_image' => 'media/import/Seagal.jpg',
    '_media_attribute_id' => '88',
    '_media_is_disabled' => 0,
    '_media_lable' => 'image',
    '_media_position' => 1,
    'media_gallery' => 0,
    'image' => 'media/import/Seagal.jpg',
    'small_image' => 'media/import/Seagal.jpg',
    'thumbnail' => 'media/import/Seagal.jpg',
  ),
)
```

**Comment by pquerner** [comment]
Maybe that should be noted somewhere in a readme.
(memory_limit shouldnt be -1 nor anything with else but "M")
(I know its a Magento thing, ..)
