### ISSUE TITLE
Required values: available_sort_by and default_sort_by

### ISSUE THREAD

**Issue by mstephens** [avstudnitz/AvS_FastSimpleImport#154]
Hello

I am not sure if this is an issue or was implemented for a specific reason (thought I'd raise it as a ticket anyway), but there seems to be a problem setting 'available_sort_by' to the standard default setting in Magento (i.e. them all). By default this works fine (using the Magento importer) as it uses the standard Magento backend model, but in the AvS code there seems a bypass for this attribute. 

More information on the issue can be seen here; http://magento.stackexchange.com/questions/34587/category-import-what-are-the-default-values-for-available-sort-by-and-default/35640

Perhaps it should be altered to allow an array of values or the setting of null (to fallback to default?).

Cheers
Matt

**Comment by jzahedieh** [comment]
FYI if you need a temporary fix I created a new module which rewrites the class with the following:

    public function validateRow(array $rowData, $rowNum)
    {
        foreach ($this->_attributes as $attrCode => $attrParams) {
            if ($attrParams['is_required'] && in_array($attrCode, $this->_indexValueAttributes)) {
                unset($this->_attributes[$attrCode]['is_required']);
            }
        }

        return parent::validateRow($rowData, $rowNum);
    }

**Comment by barbazul** [comment]
The problem here is that Magento adds a checkbox in the admin panel for "use configuration value" on some attributes. In the backend model for these attributes the request is checked to see if the flag was passed and allows null values if it was, even when the attribute itself is required.
The current import adapter is not taking this flag into consideration.

I've fixed this issue by adding an additional check in the elseif clause to check for the flag being added to the row.

I'll tidy up the code to send a PR later, but the fix is something like this:

```php
    // Attributes that allow to default to configuration values
    protected $_canUseConfigAttributes = array('available_sort_by', 'default_sort_by');
    
    public function isAttributeUsingConfig($attrCode, $rowData)
    {
        if (!in_array($attrCode, $this->_canUseConfigAttributes)) {
            return false;
        }

        $key = 'use_config_' . $attrCode;

        if (!empty($rowData[$key])) {
            return true;
        }

        return false;
    }

    public function validateRow(array $rowData, $rowNum)
    {
        // [ ... some code ...]

            // check simple attributes
            foreach ($this->_attributes as $attrCode => $attrParams) {
                if (isset($rowData[$attrCode]) && strlen($rowData[$attrCode])) {
                    $this->isAttributeValid($attrCode, $attrParams, $rowData, $rowNum);
                } elseif ($attrParams['is_required'] && !isset($this->_categoriesWithRoots[$root][$category]) 
                    && !$this->isAttributeUsingConfig($attrCode, $rowData)) {
                    $this->addRowError(self::ERROR_VALUE_IS_REQUIRED, $rowNum, $attrCode);
                }
            }

        // [ ... some code ...]

    }
```

**Comment by paales** [comment]
@barbazul This looks good :)

**Comment by barbazul** [comment]
I'll wait for #216 to get approved and closed before sending a PR for this one as I will most likely work on top of it

**Comment by diglin** [comment]
Still not merged ? Sad. I have same issue

**Comment by barbazul** [comment]
Have been using the version with my fix for a while now and have not had any issues with it.

Simply apply the patch yourself

**Comment by avstudnitz** [comment]
@barbazul I merged #216, sorry for the delay. Do you have the complete working code you are using somewhere? Just send me the file...

**Comment by avstudnitz** [comment]
@Desmaster sent me some code to fix the issue: https://gist.github.com/Desmaster/20f21eec7200dd01b408806c8af3fa54

**Comment by MickAdams** [comment]
For anyone wanting a quick fix, passing empty strings to the API (v2) seems to set the default check boxes.

available_sort_by = new string[] { "" },
default_sort_by = "",
