### ISSUE TITLE
Support for importing through category IDS

### ISSUE THREAD

**Issue by paales** [avstudnitz/AvS_FastSimpleImport#170]
As mentioned by @avstudnitz here: https://github.com/avstudnitz/AvS_FastSimpleImport/issues/135

> I'd like to have support for category IDs in that import as well as we have it in the product import already and I know it's being used - categories have no real identifier. I'd be happy to merge a pull request, unfortunately I don't have the time to implement it myself at the moment.

**Comment by pquerner** [comment]
@refaelgold So it is working with category IDs, or are your category names just "10" and "11" ?

**Comment by nhp** [comment]
As i just tested it: at least in actual versions (tried it in 1.9 and 1.14) it is working when you pass an array of category_ids into _category like _category = ['11','12','49590']. With "nested_array_support" it is correctly assigning the product to multiple categories, even in different root categories.

**Comment by nhp** [comment]
As i said yesterday: it is working, but only if you do NOT supply the _root_category key, because then it is expecting a string-path in _category and IDs are no longer working. Just to have it somewhere

**Comment by riker09** [comment]
@avstudnitz Please take this into account, when working on #290: When specifying category entity_ids as array (with nested_array_support enabled) you *MUST* omit `_root_category` or the import will fail.
