### ISSUE TITLE
getBunchSize() doesn't exist in Magento 1.6

### ISSUE THREAD

**Issue by mhauri** [avstudnitz/AvS_FastSimpleImport#179]
Function getBunchSize() doesn't exist in Mage_ImportExport_Helper_Data of Magento Version 1.6.2.0

But get's called in:
src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Category.php:1105
src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Customer.php:391
src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php:1380

Maybe update the compatibility part of README.md :-)

**Comment by antonio2604** [comment]
Hi it dosn´t work on Magento 1.6 somebody has an idea ?

**Comment by mhauri** [comment]
@antonio2604 use release 0.6.2 of AvS_FastSimpleImport for Magento version 1.6.x

**Comment by antonio2604** [comment]
Hi thanks for the info, where can I get the version.
Thanks a lot :)

**Comment by antonio2604** [comment]
Hi i have found it, but the same problem:

Call to undefined method Mage_ImportExport_Helper_Data::getBunchSize()  

:(

**Comment by just-tom** [comment]
Anyone get an answer to this?
Cheers

**Comment by paales** [comment]
As @mhauri mentioned, use the 0.6.2 branch or even better, upgrade Magento!

**Comment by just-tom** [comment]
Hi @paales thanks for the response, as @antonio2604 said, this branch hasn't actually fixed the issue. And of course the better thing to do is upgrade magento but this is for a clieant feature who are on 1.6. Do you know when the last stable release was for 1.6?? Would be very grateful. Thanks

**Comment by dzschille** [comment]
The call for getBunchSize() [was implemented in 0.6.0](https://github.com/avstudnitz/AvS_FastSimpleImport/commit/2143dafd9ab053488442d0d88ac6620382ad0516). So the last working version for Magento 1.6.x is AvS_FastSimpleImport 0.5.
