### ISSUE TITLE
Product Import Export

### ISSUE THREAD

**Issue by svishalgarg** [avstudnitz/AvS_FastSimpleImport#188]
I want to Edit Import Export Code I want to Import and Export pair of 500 Products Each .
I mean after Importing or Exporting 500 Products the page should refresh and import or export next 500 products this process should continue untill all the products import or export .

can you please help me or provide me the module like this I will be very thankful to you

**Comment by avstudnitz** [comment]
Sorry, that's out of the scope of this module.
