### ISSUE TITLE
Importing more than one custom option

### ISSUE THREAD

**Issue by maxbaldanza** [avstudnitz/AvS_FastSimpleImport#192]
This may not be an issue it may just be that I'm passing incorrect data but I'm trying to import products with multiple custom options. Importing products with one custom option seems to work correctly but when adding multiple it doesn't seem to add any. 
Have you tested the plugin with multiple custom options and have an example of how to achieve this?

**Comment by sprankhub** [comment]
I also struggled importing multiple custom options, because there is no documentation for it. But it seems to be quite straightforward. In order to import multiple custom options, you need to use multiple rows:

    $data = array(
        array(
            'sku' => '1234567',
            // this is the product you import with all your fancy attributes as shown under
            // https://avstudnitz.github.io/AvS_FastSimpleImport/products.html
        ),
        array(
            // now you use a new row for each custom option you want to add to the above product
            '_custom_option_sku'         => 'SKU',
            '_custom_option_title'       => 'TITLE',
            '_custom_option_type'        => Mage_Catalog_Model_Product_Option::OPTION_TYPE_WHATEVER,
            '_custom_option_is_required' => false,
            '_custom_option_row_title'   => 'ROW TITLE',
            '_custom_option_row_price'   => 123,
            '_custom_option_row_sku'     => 'ROW_SKU'
        )
        // add more custom options here
        // add more products here
    );

**Comment by Triyugi** [comment]
@sprankhub I am getting some problems while importing custom options. Can you please help here #390 ?
