### ISSUE TITLE
Missing IgnoreDuplicates in AvS_FastSimpleImport_Model_Import_Entity_Product

### ISSUE THREAD

**Issue by SchumacherFM** [avstudnitz/AvS_FastSimpleImport#196]
Is there a specific reason why the IgnoreDuplicate feature hasn't been implemented into class `AvS_FastSimpleImport_Model_Import_Entity_Product` ?

I've implemented it in `public function validateRow(array $rowData, $rowNum)`

```
        if (isset($this->_newSku[$rowData[self::COL_SKU]])) {
            if($this->getIgnoreDuplicates()){
                return true;
            }
            $this->addRowError(self::ERROR_DUPLICATE_SKU, $rowNum);
            return false;
        }
```

and until now it works as expected.

But I would like to know from you @avstudnitz if there is maybe any incompatibility stuff before sending you the PR.

**Comment by avstudnitz** [comment]
I don't see a reason why it shouldn't be in it. Probably we just have forgotten that and noone noticed until now. I'd be glad to merge a pull request.

**Comment by paales** [comment]
Should we ignore the return and let the row validate? Now we are return true.

**Comment by SchumacherFM** [comment]
PR #205 send
