### ISSUE TITLE
Configurable Product Import: Nested Arrays - Super Products SKU and Super Attribute Code broken

### ISSUE THREAD

**Issue by infabo** [avstudnitz/AvS_FastSimpleImport#197]
Seems like it is not possible to import Configurable Products as Nested Arrays.
I'm trying to import an configurable product with one associated simple products.

```
$import = Mage::getModel('fastsimpleimport/import');
$import->setUseNestedArrays(true)->processProductImport($configurableProducts);
```

Here an excerpt from my JSON array:
```
"_super_products_sku":["TESTSKU-35"],"_super_attribute_code":["ring_size"]
```

*Input Data contains 1 corrupt records (from a total of 1)\n:::: Product with specified super products SKU not found ::::\nIn Line(s) 1\n*

When I modify it to:
```
"_super_products_sku":"TESTSKU-35","_super_attribute_code":"ring_size"
```

it gets imported successfully. For my understanding it should be possible in terms of a nested array. Right? Or am I missing something?

**Comment by infabo** [comment]
OMG i'm going to close this issue right now. I'm just an idiot! I had forgotten "setUseNestedArrays(true)" on my "dryrunProductImport" line.....

**Comment by paales** [comment]
Good luck! :smile:
