### ISSUE TITLE
Warning: strpos() expects parameter 1 to be string, array given  in app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php on line 306

### ISSUE THREAD

**Issue by Schrank** [avstudnitz/AvS_FastSimpleImport#200]
`Warning: strlen() expects parameter 1 to be string, array given  in app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php on line 1213`

This happens if we have empty arrays, but funnily a few are filtered for some reason.

Will try to fix

**Comment by paales** [comment]
Do you mean this line?
https://github.com/avstudnitz/AvS_FastSimpleImport/blob/develop/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L348

**Comment by Schrank** [comment]
Damn. I have two lines with the posted error and 200 with the correct one. Fixed the comment.

**Comment by paales** [comment]
Cool, discussion continues in #201.
