### ISSUE TITLE
Special price issue

### ISSUE THREAD

**Issue by salman032** [avstudnitz/AvS_FastSimpleImport#202]
Hi
I setup $30 special price for a product and all goes well. But now when I try to unset the special price it set special price to "0.00". How can we unset the value of an attribute completely as it is showing $0 price of my product.

how to solve this issue.??

**Comment by paales** [comment]
@salman032 You should pass in `null` as the value (not a string, but the null value).

**Comment by avstudnitz** [comment]
If that doesn't work, try entering "###EMPTY###" or whatever you have set in the configuration (fastsimpleimport/general/symbol_for_clear_field)

**Comment by salman032** [comment]
Thanks alot paales and avstudnitz.. 
I have another issue that i want to import a bulk of data from csv to magento at once. the data variable is importing one product data at a time and if in a loop i import data evert time for each product it take a alot of time. so how can i put data in a variable and pas that only that variable once to your module ?

**Comment by paales** [comment]
@salman032 Just create a nested array with all the data and pass that into the importer.

```
$data = array(
// .. Here are multiple arrays of all your products.
);
/** @var $import AvS_FastSimpleImport_Model_Import */
$import = Mage::getModel('fastsimpleimport/import');
try {
    $import->processProductImport($data);
} catch (Exception $e) {
    print_r($import->getErrorMessages());
}
```

**Comment by paales** [comment]
Closing issue because of no response.
