### ISSUE TITLE
(SOLVED) Using _super_attribute_price_corr for multiple stores/sites

### ISSUE THREAD

**Issue by fr0x** [avstudnitz/AvS_FastSimpleImport#204]
So I recently ran into this issue and noticed a previous issue someone had opened (since closed):

https://github.com/avstudnitz/AvS_FastSimpleImport/issues/133

Unfortunately, it doesn't look like a solution was ever found (other than to use a different module).

This is probably not the most elegant solution but it does work.  As the previous person noted, the issue is with this piece of code in src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product/Type/Configurable.php

    if (!empty($rowData['_super_attribute_price_corr'])) {
      $superAttributes['pricing'][] = array(
        'product_super_attribute_id' => $productSuperAttrId,
        'value_index'   => $optionId,
        'is_percent'    => '%' == substr($rowData['_super_attribute_price_corr'], -1),
        'pricing_value' => (float) rtrim($rowData['_super_attribute_price_corr'], '%'),
        'website_id'    => 0
      );
    }

The problem is always setting website_id to 0 (which forces it to always set it as the default)

My modified piece (I also had to remove the protected from _storeCodeToId)

    if (!empty($rowData['_super_attribute_price_corr'])) {
      $rowScope = $this->_entityModel->getRowScope($rowData);
      $rowStore = Mage_ImportExport_Model_Import_Entity_Product::SCOPE_STORE == $rowScope ? $this->_entityModel->_storeCodeToId[$rowData[Mage_ImportExport_Model_Import_Entity_Product::COL_STORE]] : 0;
      $rowWebsite = $rowStore > 0 ? Mage::getModel('core/store')->load($rowStore)->getWebsiteId() : 0;
      $superAttributes['pricing'][] = array(
        'product_super_attribute_id' => $productSuperAttrId,
        'value_index'   => $optionId,
        'is_percent'    => '%' == substr($rowData['_super_attribute_price_corr'], -1),
        'pricing_value' => (float) rtrim($rowData['_super_attribute_price_corr'], '%'),
        'website_id'    => $rowWebsite
      );
    }

Basically it checks to make sure the scope is "store" scope first.  Then it attempts to retrieve the storeId for the given storeCode.  Then it loads the websiteId for that storeId.  Once we have the websiteId we can easily pass it in to the pricing piece of the superAttributes array.

Now, this requires you to send the _store code for every instance of a variable price.  As an example, here is my submitted array (paired down quite a bit to only show the required pricing pieces in regards to the configurable product).  Simple Product info not shown as that should be unaffected.

This is my default configurable product 

    [X] => Array
        (
            [sku] => mySKU1234
            [_type] => configurable
            [_attribute_set] => Default
            [_product_websites] => Array
                (
                    [0] => mystore1
                    [1] => mystore2
                )
            [price] => 299.00
            [_super_products_sku] => Array
                (
                    [0] => childsku1
                    [1] => childsku2
                    [2] => childsku3
                )

            [_super_attribute_code] => Array
                (
                    [0] => color_text
                    [1] => color_text
                    [2] => color_text
                )

            [_super_attribute_option] => Array
                (
                    [0] => White
                    [1] => Black
                    [2] => Red
                )

            [_super_attribute_price_corr] => Array
                (
                    [0] => 0.0
                    [1] => 299
                    [2] => 0.0
                )

        )

And here are my two store overrides.  My first store (mystore1) doesn't have any difference in price from the default.  However, my second store (mystore2) has it's black item as $199 more instead of $299 more.

    [X] => Array
        (

            [price] => 299.00

            [_store] => Array
                (
                    [0] => mystore1
                    [1] => mystore1
                    [2] => mystore1
                )

            [_super_products_sku] => Array
                (
                    [0] => childsku1
                    [1] => childsku2
                    [2] => childsku3
                )

            [_super_attribute_code] => Array
                (
                    [0] => color_text
                    [1] => color_text
                    [2] => color_text
                )

            [_super_attribute_option] => Array
                (
                    [0] => White
                    [1] => Black
                    [2] => Red
                )

            [_super_attribute_price_corr] => Array
                (
                    [0] => 0.0
                    [1] => 299
                    [2] => 0.0
                )

        )

    [X] => Array
        (

            [price] => 299.00

            [_store] => Array
                (
                    [0] => mystore2
                    [1] => mystore2
                    [2] => mystore2
                )

            [_super_products_sku] => Array
                (
                    [0] => childsku1
                    [1] => childsku2
                    [2] => childsku3
                )

            [_super_attribute_code] => Array
                (
                    [0] => color_text
                    [1] => color_text
                    [2] => color_text
                )

            [_super_attribute_option] => Array
                (
                    [0] => White
                    [1] => Black
                    [2] => Red
                )

            [_super_attribute_price_corr] => Array
                (
                    [0] => 0.0
                    [1] => 199
                    [2] => 0.0
                )
        )

So, basically the only changes I had to make was to the code I listed above and then sending an array of store names for how many simple products I had instead of a single line for the store name.

**Comment by paales** [comment]
Good to see you've figured it out!
