### ISSUE TITLE
media_image in array ?

### ISSUE THREAD

**Issue by hgati** [avstudnitz/AvS_FastSimpleImport#206]
![snap1](https://cloud.githubusercontent.com/assets/6913728/6311544/997a8e7a-b9a7-11e4-9ac1-c61f749242a5.jpg)

```php
$product = array(
    'sku' => '1234567',
    '_media_image' => array('img1.jpg', 'img2.jpg', 'img3.jpg'),
    '_media_attribute_id' => array(77,77,77),
    '_media_is_disabled' => array(1,0,0),
    '_media_position' => array(1,2,3),
    '_media_lable' => array('Image 1', 'Image 2', 'Image 3'),
    'image' => 'img1.jpg',
    'small_image' => 'img2.jpg',
    'thumbnail' => 'img3.jpg'
);
```

is it right ?

**Comment by BOFHELL** [comment]
is there any solution ? 
want to import some pictures , too

**Comment by avstudnitz** [comment]
Yes, looks good, if you have nested arrays enabled in the configuration.
Why don't you just try it?

**Comment by BOFHELL** [comment]
I missed the option. Tried it asap. works great. thx
