### ISSUE TITLE
Category, Sub category Tree

### ISSUE THREAD

**Issue by raj6** [avstudnitz/AvS_FastSimpleImport#213]
I want to import category and also need to import sub categories under that category, how to I do that?

**Comment by paales** [comment]
Just provide the category path you want to import and make sure the parent category is imported first.

```
MyMainCategory
MyMainCategory/Subcategory1
MyMainCategory/Subcategory1/Subsubcategory
MyMainCategory/Subcategory1/Subsubcategory/Subsubsubcategory
MyMainCategory/Subcategory2
```

Documentation can be found here: http://avstudnitz.github.io/AvS_FastSimpleImport/categories.html

**Comment by raj6** [comment]
Thank you.

**Comment by paales** [comment]
No problem :)
