### ISSUE TITLE
category import flat vs eav tables

### ISSUE THREAD

**Issue by roman204** [avstudnitz/AvS_FastSimpleImport#215]
on line 249 in 
/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Category.php
the resource model of model 'catalog/category' should be loaded, and if the flat tables are enabled it will return a object of class Mage_Catalog_Model_Resource_Category_Flat,

on line 251 the getEntityTable method is called on that object which results to the following error:
Call to undefined method Mage_Catalog_Model_Resource_Category_Flat::getEntityTable() in /app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Category.php on line 251

The avs_simple_import is defunctional if "flat tables" are enabled ?

**Comment by paales** [comment]
@roman204 I theory it should never use the flat tables, this is because the flat tables can potentially contain old data. Using the normal catalog_category_entity table is way faster (needs to be loaded in the flat table case as well).

The problem occurs when you are running the importer through a frontend controller.
- Please us an admin controller
- Simply create a shell script that runs your import
- Create your own custom observer.

**Comment by roman204** [comment]
@paales Thanks for your Response.
I am in a shell script ... 
this is my call:
Mage::getSingleton('fastsimpleimport/import')->processCategoryImport($importData);

**Comment by paales** [comment]
Could you perhaps debug why the system is still calling the flat catalog? What happens if you set setDisableFlat(true) on the category collection?

**Comment by hostep** [comment]
@roman204, you are most likely not initializing Magento using the admin store, what I usually do in shell scripts is something like this:

```
<?php

require_once('path/to/app/Mage.php');
Mage::app('admin'); // THIS IS THE IMPORTANT PART

// start importing
```

**Comment by paales** [comment]
When creating shell scripts, just create your class that inherits from Mage_Shell_Abstract, it has the initialization step build in.

**Comment by roman204** [comment]
@hostep thanks will try that.
@paales thank you, yes i want to, but in my current case its a tricky setup and environment and i can't change it so easy.

**Comment by roman204** [comment]
@hostep thank you, Mage::app('admin'); works
