### ISSUE TITLE
Wrongly assume _root is valid

### ISSUE THREAD

**Issue by barbazul** [avstudnitz/AvS_FastSimpleImport#216]
I just run an impor with a typo in the value for _root which ended in an unhandled exception:

```Warning: reset() expects parameter 1 to be array, null given in /basedir/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Category.php on line 799```

A possible fix would be:

```php
} elseif (isset($this->_categoriesWithRoots[$rowData[self::COL_ROOT]])) {
    return reset($this->_categoriesWithRoots[$rowData[self::COL_ROOT]]);
} else {
    return false;
}
```

Which causes the error ```Parent Category is not found, add parent first``` to be displayed in those cases.

**Comment by barbazul** [comment]
Looking closer at the algorithm, I guess the root validation at line 888 should be made before the parent validation, in line 866. That would be a simpler solution.

I still I think accessing array keys obtained from user input assuming they are correct is not a safe practice. My fix could stay in place even after changing the order of the validations.

**Comment by paales** [comment]
@barbazul Could you please create a pull request on the dev branch to solve this issue?

**Comment by barbazul** [comment]
I am working on it. However tests seem to be broken. After a couple of runs, fixtures start throwing foreign key duplication errors.

I have seen this sort of errors when working with EcomDev_PHPUnit in the past and they are the main reason I stopped working with fixtures on my tests. 

I will not fix these errors, I'll just add tests for my code and I leave it to you to check they all pass as a whole. Sounds good?

**Comment by avstudnitz** [comment]
@barbazul Sure, do that. Tests are running well on my system, so it won't be a problem.

**Comment by barbazul** [comment]
I did that already. :D

**Comment by feeela** [comment]
@avstudnitz What about this issue? Why is this still open? The error still occurs.

**Comment by barbazul** [comment]
Check out my PR. It wasn't accepted (or rejected), but it should be a valid fix

**Comment by avstudnitz** [comment]
Merged.
