### ISSUE TITLE
REST API endpoint

### ISSUE THREAD

**Issue by gferon** [avstudnitz/AvS_FastSimpleImport#234]
Hi,

I think it would be a cool addition to implement a Magento REST API endpoint to import / export products, would you be interested by a pull request? The code is ready, it's just not properly licensed yet, we are using it internally for now.

**Comment by avstudnitz** [comment]
I'd like that :-)

**Comment by jzahedieh** [comment]
+1

**Comment by nhp** [comment]
it is a good approach. using it the same way also. so +1
