### ISSUE TITLE
Different status on store view level not possible

### ISSUE THREAD

**Issue by phrench** [avstudnitz/AvS_FastSimpleImport#248]
My product array looks like this (shortened):

	(
	    [0] => Array
	        (
	            [_attribute_set] => Default
	            [_type] => simple
	            [visibility] => 4
	            [name] => Blue widget
	            [sku] => 123456
	            [status] => 1
				...
	        )

	    [1] => Array
	        (
	            [_store] => domain_tld_de
	            [status] => 2
	        )

	    [2] => Array
	        (
	            [_store] => domain_tld_it
	            [status] => 1
	        )

	    [3] => Array
	        (
	            [_store] => domain_tld_fr
	            [status] => 2
	        )
	)

In this example only the italian store view (domain_tld_it) should be enabled, the german and french store view should have status = disabled.

Unfortunately this doesn't work, I always end up with a disabled product in all store views (incl. default scope).
But the exact same setup with e.g. the attribute [visibility] instead of [status] will yield the desired result.

How can I enable/disable products on a store view level?

**Comment by phrench** [comment]
It looks like the last status value of the three store view arrays overwrites the previous ones. But not the default scope.

Is this behavior expected or a bug?

**Comment by mam08ixo** [comment]
Do all store views share the same website? If so, this is expected behaviour. By default, the *status* attribute is set to website scope. With all store views associated to different websites it works fine for me:
```php
$data = array(
    array(
        'sku'            => '123456',
        '_type'          => 'simple',
        '_attribute_set' => 'Default',
        '_store'         => array(null, 'domain_tld_de', 'domain_tld_it', 'domain_tld_fr'),
        'status'         => array('1', '2', '1', '2'),
    ),
);

/** @var AvS_FastSimpleImport_Model_Import $import */
$import = Mage::getModel('fastsimpleimport/import');
$import
    ->setBehavior(Mage_ImportExport_Model_Import::BEHAVIOR_REPLACE)
    ->setUseNestedArrays(true);
$import->processProductImport($data);
```

**Comment by phrench** [comment]
Yes, all three store views share the same website.

You mean it's expected behavior for AvS_FastSimpleImport?
Because it's no problem to manually assign a different status to different store views sharing the same website.

**Comment by mam08ixo** [comment]
> It's no problem to manually assign a different status to different store views sharing the same website.

I disagree. In a plain Magento installation, for store views sharing the same website, you cannot set differing *status* values for the same product on store view scope. If you change the status in one scope, same value is applied for all other store views within the given website (just like it happens during your import).

However, try importing your product using standard CSV import and check if either status are set according to your expectations or just like they are set using the `AvS_FastSimpleImport` wrapper.

**Comment by phrench** [comment]
> In a plain Magento installation, for store views sharing the same website, you cannot set differing status values for the same product on store view scope. If you change the status in one scope, same value is applied for all other store views within the given website (just like it happens during your import).

After searching for information about this I can confirm this is correct. Strangely, in our install changing status on store view level works, although the attribute itself has scope "Website".

I'll definitely have to go with 'Visibility' instead of 'Status' then.

Thanks for your help!
