### ISSUE TITLE
Get imported category/product entity_id after successful import

### ISSUE THREAD

**Issue by pquerner** [avstudnitz/AvS_FastSimpleImport#250]
Is it possible to receive the product/category entity_id after successful import?
Eg. If I want to do some extra work after the import but I need the entity_ids so I can manipulate / alter stuff.

**Comment by paales** [comment]
An example where this happens:
https://github.com/ho-nl/Ho_Import/blob/master/app/code/community/Ho/Import/Model/Observer.php#L31

**Comment by pquerner** [comment]
Thanks @paales 

So broken down: you observe the ```catalog_product_import_finish_before``` event (and do some custom logic there (eg. you have an attribute which is set when you use your import)) and fetch the product info and save it somewhere else. 

Same logic would apply to category creation process (with a different event-name) I assume.

Clever. :+1:
