### ISSUE TITLE
Set product attribute to "use_default"

### ISSUE THREAD

**Issue by sbruggmann** [avstudnitz/AvS_FastSimpleImport#257]
I can import product informations to multiple stores like
```
$data[] = array(
  '_store' => array('base', 'de'),
  'name' => array('base name', 'german name')
);
```

But how i can remove a store specific attribute later and set it to "use_default"?
The following don't work.
```
$data[] = array(
  '_store' => array('base', 'de'),
  'name' => array('base name', false)
);
```

I'm very happy if there is a solution.

Regards,
Stefan

**Comment by avstudnitz** [comment]
Have you tried `###EMPTY###` instead of `false`? You can configure the symbol used for clearing a field in the configuration.

**Comment by sbruggmann** [comment]
Thank you for the fast reply!

That is what i was searching for :)
