### ISSUE TITLE
5a9ca8d causing problems with EE because EE-Model is used instead of fsi

### ISSUE THREAD

**Issue by nhp** [avstudnitz/AvS_FastSimpleImport#268]
commit 5a9ca8d causes a problem with EE because in my case there is ```enterprise_importexport/import_entity_product``` in the $validTypes array. Will investigate it further.

**Comment by nhp** [comment]
In this case it is caused by Enterprise_ImportExport. That is depending on Mage_ImportExport. 
Adding ```<depends><Enterprise_ImportExport/></depends>``` to ```AvS_FastSimpleImport.xml``` is working, but not really good because then it is only usable within an Enterprise Edition. Alternative would be ```<depends><Mage_ImportExport/></depends>``` and renaming it to something "after" Enteprise_ImportExport.

**Comment by avstudnitz** [comment]
Aren't community modules always loaded after all Mage_* and Enterprise_* modules?

**Comment by paales** [comment]
@avstudnitz Unfortunately not, installation instructions for Enterprise should include:

```
<AvS_FastSimpleImport>
    <depends>
        <Enterprise_ImportExport/>
    </depends>
</AvS_FastSimpleImport>
```

**Comment by nhp** [comment]
@avstudnitz that is exactly what i thought, but it is not true :(

**Comment by diglin** [comment]
I confirm the issue

```
PHP Fatal error:  Call to undefined method Enterprise_ImportExport_Model_Import_Entity_Product::setBehavior() in /vagrant/htdocs/magento/src/app/code/community/AvS/FastSimpleImport/Model/Import.php on line 83
```
