### ISSUE TITLE
Adding remote images to local, then importing

### ISSUE THREAD

**Issue by seansan** [avstudnitz/AvS_FastSimpleImport#273]
Hi, would it bee an option to add an option to import remote images also? We get data lists with remote image locations. Would be great if remote images are detected, then downloaded to var/import and then uploaded in the system from there. Maybe me more to it ... but would be god to have maybe

**Comment by avstudnitz** [comment]
This does already work. The usage is described in #108. Sorry there is no easily findable documentation about that feature yet.
