### ISSUE TITLE
Enterprise importexport conflicts with avs import

### ISSUE THREAD

**Issue by mbijnsdorp** [avstudnitz/AvS_FastSimpleImport#275]
It seems our fork hasn't been up to date for a while now, but a change introduced here: https://github.com/avstudnitz/AvS_FastSimpleImport/commit/5436c42c5b3012759586b19c96c499c31709431c results in the Enterprise importexport model being initialized instead of the avs model. Both modules have their configuration for `importexport/import_entities/catalog_product/model_token` and depend on `Mage_ImportExport`, but as Enterprise comes later alphabetically, its configuration is eventually used.

I've come up with only two solutions thus far:
1. Make the module depend on Enterprise importexport
2. Restore model initialization to what it was:
 `$entityAdapter = Mage::getModel('fastsimpleimport/import_entity_product');`

As the first option would make this module incompatible with CE, I would go with option 2.

Thoughts?

**Comment by paales** [comment]
Please see https://github.com/avstudnitz/AvS_FastSimpleImport/issues/268

**Comment by paales** [comment]
Maybe this should be added to the installation instructions.

**Comment by mbijnsdorp** [comment]
Oh sorry, quickly scanned the issue list for something similar, but seems I missed it.
