### ISSUE TITLE
Issue with multiselect option import

### ISSUE THREAD

**Issue by shabeer-ali** [avstudnitz/AvS_FastSimpleImport#283]
Hi,
I am trying to import product with multiselect option and it is importing all options.But it is selecting only first value instead of given all values.The following is array structure for age multiselect attribute. I am trying to import without UI. How i can import products with all option selected. 
                    [weight] => 1
                    [color] => Origami Rose
                    [is_in_stock] => 1
                    [age] => Array
                        (
                            [0] => 0 Months
                            [1] =>  1 Months
                            [2] =>  3 Months
                            [3] =>  6 Months                    
                        )

**Comment by avstudnitz** [comment]
It should work this way. Do you have the nested array import format enabled?

**Comment by shabeer-ali** [comment]
Thank you for confirming the array structure.Now it is working.The issue was with leading whitespace in array values.
