### ISSUE TITLE
Not selecting default image after import.

### ISSUE THREAD

**Issue by shabeer-ali** [avstudnitz/AvS_FastSimpleImport#284]
Hi,
I am trying to import multiple images to image gallery.It is importing all images to gallery but it is not selecting the default image.So i have to go to each products to select the default image.Is this plugin support default image selection or something wrong with my code?. I am using Array import method.

**Comment by mbijnsdorp** [comment]
During the import, do you also provide image, small_image and thumbnail in your row data?

**Comment by jzahedieh** [comment]
Is it all images or just some?

**Comment by shabeer-ali** [comment]
Yes it doing for all. The following is the sample row structure which i am trying. The following code imports all images properly.But not selecting default image.Is there any issue if the url is external ? 


$image1='http://d6js1m4bqyj43.cloudfront.net/media/catalog/product/resized/11318_zoom_0.jpg';
$image2='http://d6js1m4bqyj43.cloudfront.net/media/catalog/product/resized/11319_thumb_0.jpg';

$data = array(array(
    'sku' => 'DL/68308220',
    '_media_image' => array($image1,$image2),
    '_media_attribute_id' => array(88,88),
    '_media_is_disabled' => array(0,0),
    '_media_position' => array(1,2),
    '_media_lable' => array('image1','image2'),
    'image' => $image1,
    'small_image' =>$image1,
    'thumbnail' => $image1
));



try {

    $import = Mage::getModel('fastsimpleimport/import');
    $import->processProductImport($data);
    
      echo "Messages: " . PHP_EOL;
        echo $import->getErrorMessage();

    /** @var $import AvS_FastSimpleImport_Model_Import */
} catch (Exception $e) {
    print_r($import->getErrorMessages());
}

**Comment by avstudnitz** [comment]
Please just use the filename for `image`, `small_image` and `thumbnail`, i.e. `'11318_zoom_0.jpg'`. See a working example at #108 (yes, that should go into the documentation).

**Comment by shabeer-ali** [comment]
Thanks Andreas. Now its working perfectly.

**Comment by avstudnitz** [comment]
Great!
