### ISSUE TITLE
Import Via CSV

### ISSUE THREAD

**Issue by elliotth123** [avstudnitz/AvS_FastSimpleImport#300]
I am new to AVS_FastSimpleImport and I am having issues figuring out how to exactly set it up. I am importing/updating from a csv file. Does anyone have an example of a php file that they use? 
I have reviewed everything on here but am obviously missing large sections, mostly from the importing from a single csv. I am an ex magmi user so most of my csv files are based from that.

**Comment by seansan** [comment]
https://github.com/avstudnitz/AvS_FastSimpleImport/issues/445#issuecomment-667009870
