### ISSUE TITLE
_store parameter as array, is it possible?

### ISSUE THREAD

**Issue by pabloblazquez** [avstudnitz/AvS_FastSimpleImport#301]
I have one store view for each language in my Magento. To import the differents values for each language, I'm trying this:

```
$data = array(
    ... (other fields)
    $product_data_config['_store'] = array('es', 'eu', 'en');
    $product_data_config['name'] = array('spanish name', 'basque name', 'english name');
    .... (other fields)
);
```

When I try to import that, I receive the error:
**Fatal error: Uncaught exception 'Exception' with message 'Warning: strlen() expects parameter 1 to be string, array given in xxxx\app\code\community\AvS\FastSimpleImport\Model\Import\Entity\Product.php on line 1397**

This error is caused by "_store" field, becouse it is an array instead of a string.
¿It is not allowed to have nested array functionality with store views? Any solution or workarround for this?

Thanks in advice!

**Comment by pquerner** [comment]
Try it like this:

```
data
   0
      _store = en
      name = english name
   1
      _store = es
      name = spanish name

etc.
```

**Comment by pabloblazquez** [comment]
Thanks @pquerner, finally I used your proposed structure:
`    [0] => Array
        (
            [sku] => 21620320
            [_attribute_set] => Default
            [_type] => configurable
            [_product_websites] => xxxx
            [name] => spanish name
              ...
              **** notice no _store here as we want those as base values ****
              ...
        )

    [1] => Array
        (
            [sku] => 
            [_store] => en
            [name] => english name
              ...
              **** english fields. Notice that "sku" must be empty ****
              ...
        )
`
