### ISSUE TITLE
Import different prices for different sub domain (view store)

### ISSUE THREAD

**Issue by FTEyurchenko** [avstudnitz/AvS_FastSimpleImport#314]
Is it possible to import it's own price for each view store? For some reason, when I try to do it,the last value in csv file overrides it for every store. Is it ever possible? Thank you.

**Comment by avstudnitz** [comment]
Depends on your Magento Setup. By default, you only have one global price. You can change a config setting so you have a price per website. Still, if you import a price for one store, it gets transferred to all other stores of the same website.

**Comment by inluxc** [comment]
Not if you have price per store view scope. https://www.magentocommerce.com/magento-connect/store-view-pricing.html

**Comment by BSSCommerce** [comment]
I am not sure but you can set different prices for a product per store view of each store 
https://www.magentocommerce.com/magento-connect/multistore-pricing-extension.html

**Comment by stefan68** [comment]
You can **[contact BSSCommerce](http://bsscommerce.com/contacts)** to get support.
There is an extension for you to try and I think it will help: Multiple Store View Pricing extension.
Try it now:
-  http://bsscommerce.com/magento-multistore-pricing.html
- For Magento 2 platform:  http://bsscommerce.com/magento-multiple-store-view-pricing-for-magento-2.html
