### ISSUE TITLE
Customer Import - website does not exists

### ISSUE THREAD

**Issue by Raphomee** [avstudnitz/AvS_FastSimpleImport#329]
Hi,

discoverd a problem importing customer data.

I have 2 Stores.

Store 1 works fine.
Store 2 got the following error:
###
[Invalid value in Website column (website does not exists?)]
###

If I try to import the file for store 2 manually in Magento-Admin (System -> Import/Export -> Import) it can be imported without any errors.

Any idea why this happens ?

Kind regards,
Raphael Gehlhaar

**Comment by avstudnitz** [comment]
@Raphomee please proved a sample of the import data (anonymized) so we can check if that may be the cause.

**Comment by Raphomee** [comment]
file attached

**Comment by avstudnitz** [comment]
@Raphomee Where? Don't see it?

**Comment by Raphomee** [comment]
now ... had to rename it to *.txt


[error.txt](https://github.com/avstudnitz/AvS_FastSimpleImport/files/352327/error.txt)

**Comment by Raphomee** [comment]
Hi,

I checked the following File: app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Customer.php

Line: 321
            } elseif (!isset($this->_websiteCodeToId[$website])) {
                $this->addRowError(self::ERROR_INVALID_WEBSITE, $rowNum);
            } else {


added:
				var_dump($this->_websiteCodeToId);
				die();

this Array is missing one of our stores / websites we added in magento.
Does your module cache this anywhere?

Kind regards,
Raphael Gehlhaar

**Comment by avstudnitz** [comment]
Just for clarification: I don't see a second store or website in the data you provided. Does the error occur with this exact file too, and which error exactly?

AvS_FastSimpleImport doesn't have such a cache. The code in question is from Mage_ImportExport originally. Please try to remove the /var/cache/ folder completely.

**Comment by Raphomee** [comment]
We are using 2 CSV Files (for each store one file)
First file works fine, second got this error.

Clearing /var/cache did not help

**Comment by Raphomee** [comment]
Found the problem.
Memcached cached our old Websites and Stores although we deactivated all cache in backend.
resettet memcache Cache and now it works.
