### ISSUE TITLE
cron import clears related/upsell/crosssell items assigned through backend

### ISSUE THREAD

**Issue by martijnooms** [avstudnitz/AvS_FastSimpleImport#357]
Hi,

I'm having problems with magento 1.9.2.4.
I'm doing a periodic cron product import with AvS connector, but everytime the cron is executed, my product information is updated automatically, but the related products I assigned to the simple product through the backend are cleared, so basically i should do this every hour, to reassign all the products. The cron runs every hour for synchronisation with accounting programm
Is there a way to ignore this part of a product (f.e. "ignore related => true"), so that the relations I assign there aren't cleared every time the cron runs?

thank you in advance
Martijn

**Comment by rbrown** [comment]
Which import behaviour are you using? http://avstudnitz.github.io/AvS_FastSimpleImport/options.html

> Import Behavior
> 
> Select from:
> 
> Append Complex Data: create new products, modify existing products
> Replace Existing Complex Data: create new products, delete and recreate existing products

**Comment by damienwebdev** [comment]
I actually have the same exact functionality occuring on 1.9.2.4. I was using `Replace Existing Complex Data`. Is that not the correct option to be using to just update/create existing products?

**Comment by damienwebdev** [comment]
Any movement on this @rbrown ? I'm still having this issue and it's a blocker for one of my implementations. I can try and debug and submit a PR, but I figure you guys know the codebase better than I do.

**Comment by rbrown** [comment]
I'm not a developer, but I was digging around in this for myself the other day. One way around it would be to not supply the attribute you want left alone. So, don't supply _links_related_sku unless all your rows are supplying a value for that?

**Comment by damienwebdev** [comment]
Sure. I guess I can just leave it as 'Append' with an empty field and I'd be good to go?

**Comment by avstudnitz** [comment]
Yes, you should use "Append" if you want to keep existing links or other complex data.
