### ISSUE TITLE
Can we use external image path to import media images?

### ISSUE THREAD

**Issue by bijalbhavsar** [avstudnitz/AvS_FastSimpleImport#362]
Hi Astudnitz,

Great work done by you! 

This is not an issue actually, its a feature!

Are we able to use external http image path to import product images with your extension? As we are using this extension since long we have 100k of products for that we were receiving external image path and need to import through AVS Fast simple import.

Thanks for your contribution!

Regards,
Bijal B.

**Comment by avstudnitz** [comment]
It is supported, see #108. I know it's missing in the documentation.
