### ISSUE TITLE
add stock_id for qty updating

### ISSUE THREAD

**Issue by seansan** [avstudnitz/AvS_FastSimpleImport#363]
Is it possible to add a stock_id column during import

when found

then update qty for that stock_id

**Comment by paales** [comment]
@seansan Yeah, it is already supported. https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L1296-L1302

**Comment by seansan** [comment]
cool tthx!
