### ISSUE TITLE
Is FastSimpleImport able to import Catalog price rules?

### ISSUE THREAD

**Issue by Sh3rman** [avstudnitz/AvS_FastSimpleImport#365]
Hello,

I want to import Gift cards products in Promotions->Catalog Price Rules area.

Is the extension able to do that?

**Comment by avstudnitz** [comment]
No, sorry. You can see an overview of what we can import at http://avstudnitz.github.io/AvS_FastSimpleImport/.

**Comment by sibbl** [comment]
As this was closed without bringing up the question whether this feature is planned/required, I assume that it will never make its way into the extension. Am I right, or are you open for pull requests on this topic?

**Comment by avstudnitz** [comment]
I don't see this as a core feature which is needed by many, but I wouldn't object a pull request.
