### ISSUE TITLE
French Characters

### ISSUE THREAD

**Issue by Zippo90** [avstudnitz/AvS_FastSimpleImport#371]
Hi,
I must import product for a french site. I've a problem to import special char.

For example:
'description' => utf8_encode("ç")

in backend I see this:
Ã§

Why?

**Comment by avstudnitz** [comment]
If you have the file in UTF-8, the `utf8_encode` command isn't needed. I have no problems importing German umlauts like this:

````
        'name' => 'Tüte',
````

**Comment by Zippo90** [comment]
Thanks, you're right. It works!
