### ISSUE TITLE
Unable to import custom options.

### ISSUE THREAD

**Issue by Triyugi** [avstudnitz/AvS_FastSimpleImport#390]
Custom options are not being imported. When I am checking with `dryrun`, no error found. But When importing all data imported except custom options. 

Array is something like that:

```
$data[] = array(
		'sku' => (string) $product->code,
		'_type' => 'simple',
		'_attribute_set' => 'Default',
		'_product_websites' => 'base',
		'name' => (string) $product->name,
		'price' => (string) $product->price_list,
		'description' => (string) $product->desc,
		'short_description' => 'NA',
		'weight' => (string) $product->weight,
		'status' => 1,
		'visibility' => 4,
        'tax_class_id' => 2,
        'qty' => (string) $product->stock,
		array(
        // now you use a new row for each custom option you want to add to the above product
			'_custom_option_sku'         => (string) $product->subproducts->subproduct->code,
			'_custom_option_title'       => 'Size',
			'_custom_option_type'        => 'drop_down',
			'_custom_option_is_required' => false,
			'_custom_option_row_title'   => (string) $product->subproducts->subproduct->type1,
			'_custom_option_row_price'   => 0,
			'_custom_option_row_sku'     => (string) $product->subproducts->subproduct->code
		)
	);
```

Result of `dryrun` is as follows:

>array(1) { [0]=> array(14) { ["sku"]=> string(5) "30848" ["_type"]=> string(6) "simple" ["_attribute_set"]=> string(7) "Default" ["_product_websites"]=> string(4) "base" ["name"]=> string(61) "Tuğba Mevsimlik Cepken Görünümlü Elbise G5180 Kırmızı" ["price"]=> string(8) "370.3518" ["description"]=> string(2085) "
Ürün Bilgisi" ["short_description"]=> string(2) "NA" ["weight"]=> string(3) "0.4" ["status"]=> int(1) ["visibility"]=> int(4) ["tax_class_id"]=> int(2) ["qty"]=> string(1) "2" [0]=> array(7) { ["_custom_option_sku"]=> string(6) "123586" ["_custom_option_title"]=> string(4) "Size" ["_custom_option_type"]=> string(9) "drop_down" ["_custom_option_is_required"]=> bool(false) ["_custom_option_row_title"]=> string(2) "42" ["_custom_option_row_price"]=> int(0) ["_custom_option_row_sku"]=> string(6) "123586" } } } Input is OKMessages: Input Data contains 0 corrupt records (from a total of 7)

**Comment by Triyugi** [comment]
When I have debugged in `/Model/Import/Entity/Product.php` as following:

```
protected function _createDropdownAttributeOptions()
    {
		var_dump($this->getDropdownAttributes());
```

It returns blank as: `array(0) { }`.

**Comment by sprankhub** [comment]
I think your nesting is wrong. Your example should probably work like that:

    $data[] = array(
        'sku'               => (string)$product->code,
        '_type'             => 'simple',
        '_attribute_set'    => 'Default',
        '_product_websites' => 'base',
        'name'              => (string)$product->name,
        'price'             => (string)$product->price_list,
        'description'       => (string)$product->desc,
        'short_description' => 'NA',
        'weight'            => (string)$product->weight,
        'status'            => 1,
        'visibility'        => 4,
        'tax_class_id'      => 2,
        'qty'               => (string)$product->stock
    );
    $data[] = array(
        // now you use a new row for each custom option you want to add to the above product
        '_custom_option_sku'         => (string)$product->subproducts->subproduct->code,
        '_custom_option_title'       => 'Size',
        '_custom_option_type'        => 'drop_down',
        '_custom_option_is_required' => false,
        '_custom_option_row_title'   => (string)$product->subproducts->subproduct->type1,
        '_custom_option_row_price'   => 0,
        '_custom_option_row_sku'     => (string)$product->subproducts->subproduct->code
    );

Could you please check and give me feedback if that works?

**Comment by Triyugi** [comment]
@sprankhub Thanks. Its working now. My code had nesting issue.
