### ISSUE TITLE
Import custom attributes.

### ISSUE THREAD

**Issue by Triyugi** [avstudnitz/AvS_FastSimpleImport#399]
I am using [Mageworx Advanced Product Option](https://www.mageworx.com/advanced-product-options-magento-extension.html). This plugin generates some custom fields which when I am trying to import but not success.

When I am using following line, import exits without throwing any error:

`'_custom_option_template_id' => 1`

**Comment by sprankhub** [comment]
Is this attribute a normal product attribute from `eav_attribute`? Then this should work, although I think you need to skip the underscore for your custom attributes. Mind that you may need to enable the auto creation of attribute values for this attribute as well.

**Comment by Triyugi** [comment]
@sprankhub  Thanks, I have resolved that issue by defining all custom fields in import model.

**Comment by IonutGorgos** [comment]
Hello @Triyugi,

How you defined all custom fields in import model and where? 
Thanks.
