### ISSUE TITLE
Import field qty_increments

### ISSUE THREAD

**Issue by riker09** [avstudnitz/AvS_FastSimpleImport#4]
I don't know if it's related to your module but I cannot import values for the qty_increment feature. I have data like the following:

```
$data = array(
    // Import data
);

$data['qty_increments'] = 40;
$data['enable_qty_increments'] = true;
$data['use_config_qty_increments '] = false;
$data['use_config_enable_qty_increments'] = false;
```

From my understanding the above code should set the value for qty_increments to 40, set the field "Use Qty Increments" ("Verpackungseinheiten verwenden") to `TRUE` and uncheck the checkboxes for "use configuration settings"  so that my custom settings take effect. Unfortunately, it doesn't, nothing happens at all.

All other fields get set properly. The PDF file from Vinai Kopp states on page 19 a list of fields, I've taken the fieldnames from there.

**Comment by krlecarp** [comment]
Peter, thanks for the hacky-enough-for-me-cuz-it's-works fix as long as I'm using modules and not overwriting core files.  Was a more elegant solution ever discovered for this?
