### ISSUE TITLE
Add License Information To composer.json

### ISSUE THREAD

**Issue by sprankhub** [avstudnitz/AvS_FastSimpleImport#405]
Currently, a warning is shown on https://packagist.org/packages/avstudnitz/fast-simple-import:

> There is no license information available for the latest version (0.8.2) of this package.

**Comment by avstudnitz** [comment]
We need a new release to fix that. It's already prepared in composer.json in the master branch.

**Comment by sprankhub** [comment]
Oh okay, thanks. I just checked the default branch (develop).
