### ISSUE TITLE
How to stop import?

### ISSUE THREAD

**Issue by Triyugi** [avstudnitz/AvS_FastSimpleImport#406]
If import is in progress and I want to stop it, how it can be possible?

**Comment by sprankhub** [comment]
It depends on where you started it. On the CLI, you could of course use CTRL+C. From a web interface, it is not really possible.
This should not be an issue during dry run. But mind that if you stop the real import, you may end up with orphaned rows in the database.

**Comment by Triyugi** [comment]
@sprankhub OK. Thanks. Will it stop when the internet connection disturbed?

**Comment by sprankhub** [comment]
No, the process should keep running on the server AFAIK.
