### ISSUE TITLE
Kategorien - Reset von manuellen Zuweisungen

### ISSUE THREAD

**Issue by Golibert** [avstudnitz/AvS_FastSimpleImport#418]
Wie kann man während dem Import durch AVS verhindern kann, dass nachträgliche Änderungen bzw. zusätzliche manuelle Kategorie Zuweisungen beim nächsten Import gelöscht werden?

**Comment by Golibert** [comment]
Will soviel heissten, aus dem Import wird in die Kategorie ROOT/ARTIKEL importiert, aber ich platziere den Artikel nachträglich noch in die Kategorie ROOT/SONDERANGEBOTE. Beim nächsten Durchlauf bzw. Update durch den Import bleibt nur die ROOT/ARTIKEL Kategorie zugewiesen. Wie schaffe ich es, dass die Kategorie SONDERANGEBOTE ebenfalls zugewiesen bleibt?

**Comment by avstudnitz** [comment]
Could you switch to English so others can read it too?
You need to set the Import Behavior to "Append" instead of "Replace" to achieve that.

**Comment by Golibert** [comment]
Appreciate the input, thanks. That did it.
