### ISSUE TITLE
Conflict with Module Inchoo_PHP7

### ISSUE THREAD

**Issue by lucasalcantara** [avstudnitz/AvS_FastSimpleImport#420]
I am running the module [Inchoo_PHP7](https://github.com/Inchoo/Inchoo_PHP7) to use PHP7 in my Magento project. I was trying to run this simple [example ](http://avstudnitz.github.io/AvS_FastSimpleImport/usage.html) and after calling the method to import I am getting this error `Fatal error: Call to undefined method Inchoo_PHP7_Helper_Data::unEscapeCSVData() ` anyone knows how to fix it without stopping using Inchoo_PHP7?

**Comment by hostep** [comment]
@lucasalcantara, this sounds like a duplicate of https://github.com/avstudnitz/AvS_FastSimpleImport/issues/411, have you installed security patch SUPEE-7405 on this instance?
It would surprise me if this is caused by `Inchoo_PHP7` to be honest...

**Comment by lucasalcantara** [comment]
Thanks @hostep, it is working now.
