### ISSUE TITLE
Could we upload products using 1 data line directly to muliple _product_websites

### ISSUE THREAD

**Issue by seansan** [avstudnitz/AvS_FastSimpleImport#445]
Could we upload products using 1 data line directly to muliple _product_websites?

Also see; https://magento.stackexchange.com/questions/318741/magento-1-import-products-directly-to-multiple-websites-using-csv-import

**Comment by avstudnitz** [comment]
Yes, see our documentation at http://avstudnitz.github.io/AvS_FastSimpleImport/options.html, section "Support Nested Arrays for Import":
```
$data = array(
    array(
        'sku' => '1234567',
        '_type' => 'simple',
        '_attribute_set' => 'Default',
        '_product_websites' => array('de', 'en', 'fr'),
        'name' => 'Default',
        'price' => 0.99,
        'description' => 'Default',
        'short_description' => 'Default',
        'colors' => array('green', 'silver')
        'weight' => 0,
        'status' => 1,
        'visibility' => 4,
        'tax_class_id' => 2,
        'qty' => 76,
    ),
)
```

**Comment by seansan** [comment]
And when using csv file?

**Comment by avstudnitz** [comment]
This module doesn't support using a CSV file. You'd have to implement that yourself.
